ShoppingApp.WebMVC/Areas/Admin/Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Entities.Models;

namespace ShoppingApp.WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly UserManager<User> _userManager;

        public HomeController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            string userId = _userManager.GetUserId(User).ToString();

            var user = await _userManager.FindByIdAsync(userId);


            return View();
        }
    }
}

ShoppingApp.WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Services.Abstract;
using ShoppingApp.WebMVC.Models;

namespace ShoppingApp.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _productService;

        public HomeController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(string category, int page = 1)
        {
            const int pageSize = 6;

            var products = _productService.GetProductsByCategory(category, page, pageSize);
            var totalItems = _productService.GetCountByCategory(category);
            var model = new ProductListModel()
            {
                Products = products,
                PageInfo = new PageInfo()
                {
                    TotalItems = totalItems,
                    CurrentPage = page,
                    ItemPerPage = pageSize,
                    CurrentCategory = category
                }
            };
            return View(model);
        }
    }
}

ShoppingApp.WebMVC/ViewComponents/CategoryListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingApp.Services.Abstract;
using ShoppingApp.WebMVC.Models;

namespace ShoppingApp.WebMVC.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _categoryService.Quarayable().Where(x => x.IsActive && !x.IsDeleted)
                .Include(x => x.ProductCategories)
                .Select(x => new CategoryModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Count = x.ProductCategories.Count(i => i.CategoryId == x.Id)
                }).ToList();

            return View(categories);
        }
    }
}

ShoppingApp.WebMVC/ViewComponents/FeaturedProductListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingApp.Services.Abstract;

namespace ShoppingApp.WebMVC.ViewComponents
{
    public class FeaturedProductListViewComponent : ViewComponent
    {
        private readonly IProductService _productService;

        public FeaturedProductListViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productService.Quarayable()
                .Include(x => x.Currency)
                .Where(x => x.IsFeatured).Take(5).ToList();
            return View(products);
        }

    }
}

ShoppingApp.WebMVC/Views/Home/Index.cshtml
@model ShoppingApp.WebMVC.Models.ProductListModel
<!-- sidebar start -->
<div id="sidebar" class="col-md-3">

    @await Component.InvokeAsync("CategoryList")

    @await Component.InvokeAsync("FeaturedProductList")

</div>
<!-- sidebar end -->
<!-- right column start -->
<div class="col-md-9">

    <div class="row">

        <div class="col-md-12 wow fadeIn">
            <div class="row product-results">
                <div class="product-results">
                    <div class="col-xs-8">
                        <p class="woocommerce-result-count">Showing 1–3 of @Model.PageInfo.TotalItems results</p>
                    </div>
                </div>
            </div>
        </div>



        @foreach (var item in Model.Products)
        {
            <partial name="_product" for="@item" />
        }

        <div class="col-md-12 wow fadeIn">
            <div id="pagination" class="row text-center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        @for (int i = 1; i <= Model.PageInfo.TotalPages(); i++)
                        {
                            <li class="@(i == Model.PageInfo.CurrentPage ? "active" :"")"><a href="/?page=@i">@i</a></li>
                        }
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

</div>
<!-- right column end -->