ShoppingApp.WebMVC/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Core.Utilities.Hashing;
using ShoppingApp.Data.Abstract;
using ShoppingApp.Entities.Dtos;
using ShoppingApp.Entities.Models;
using ShoppingApp.Services.Abstract;

namespace ShoppingApp.WebMVC.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<User> _signInManager;
        private readonly ICartService _cartService;

        public AuthController(UserManager<User> userManager, SignInManager<User> signInManager, IUnitOfWork unitOfWork, ICartService cartService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _unitOfWork = unitOfWork;
            _cartService = cartService;
        }

        public IActionResult Register()
        {
            return View(new UserRegisterDto());
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterDto model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var exist = await _userManager.FindByEmailAsync(model.Email);

            if (exist != null)
            {
                ModelState.AddModelError("", "Email Kullanılmaktadır");
                return View(model);
            }


            var user = new User
            {
                UserName = model.Email.ToString(),
                FirstName = model.FirstName,
                LastName = model.LastName,
                NormalizedUserName = model.Email.ToUpper(),
                Email = model.Email,
                NormalizedEmail = model.Email.ToUpper(),
                PhoneNumber = "0",
                ImageUrl = "profile.png",
                EmailConfirmed = true,
                PhoneNumberConfirmed = true,
                SecurityStamp = Guid.NewGuid().ToString(),
            };

            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {

                await _userManager.AddToRoleAsync(user, "User");
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new UserLoginDto());
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDto model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = await _userManager.FindByEmailAsync(model.Email);
            if (user == null)
            {
                ModelState.AddModelError("notAvailable.", "Hesap Bulunamadı");
                return View(model);
            }

            var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, false, false);

            if (result.Succeeded)
            {
                var hasCart = await _cartService.AnyAsync(x => x.UserId == user.Id);

                if (!hasCart)
                {
                    var cart = new Cart()
                    {
                        UserId = user.Id,
                    };
                    await _cartService.AddAsync(cart);

                    await _unitOfWork.SaveChangesAsync();
                }

                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError(".", "Beklenmedik Hata Oluştu. Tekrar Deneyiniz.");

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ViewResult AccessDenied() => View();
    }
}

ShoppingApp.WebMVC/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IyzipayCore;
using IyzipayCore.Model;
using IyzipayCore.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Data.Abstract;
using ShoppingApp.Entities.Models;
using ShoppingApp.Services.Abstract;
using ShoppingApp.WebMVC.Models;

namespace ShoppingApp.WebMVC.Controllers
{
    [Authorize]
    public class CartsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICartItemService _cartItemService;
        private readonly IOrderService _orderService;

        public CartsController(UserManager<User> userManager, ICartService cartService, ICartItemService cartItemService, IOrderService orderService, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _cartService = cartService;
            _cartItemService = cartItemService;
            _orderService = orderService;
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {

            var cart = await Cart();

            var model = new CartViewModel()
            {
                Cart = cart,
                TotalPrice = (decimal) cart.CartItems.Sum(x=> x.Quantity * x.Product.Price)
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int productId, int qty = 1)
        {
            var cart = await Cart();

            await _cartItemService.AddToCart(cart, productId, qty);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int productId)
        {
            var cart = await Cart();

            await _cartItemService.RemoveFromCart(cart, productId);

            return Json(new { Success = true });
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            var cart = await Cart();

            var model = new OrderModel()
            {
                CartModel = new CartViewModel()
                {
                    Cart = cart,
                    TotalPrice  = (decimal) cart.CartItems.Sum(x=> x.Product.Price * x.Quantity)
                }
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderModel model)
        {
            var cart = await Cart();
            var user = await _userManager.GetUserAsync(HttpContext.User);


            model.CartModel = new CartViewModel()
            {
                Cart = cart,
                TotalPrice = (decimal)cart.CartItems.Sum(x => x.Product.Price * x.Quantity)
            };

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Payment 
            var payment = PaymentProcess(model);
            if (payment.Status.ToUpper() == "SUCCESS")
            {
                await SaveOrder(model, payment, user.Id);
                await ClearCart(user.Id);
                await _unitOfWork.SaveChangesAsync();
                return View("Success");
            }


            return View(model);
        }

        private async Task ClearCart(int userId)
        {
            await _cartService.ClearCartItems(userId);
        }

        private async Task SaveOrder(OrderModel model, Payment payment, int userId)
        {
            var order = new Order()
            {
                OrderNumber = new Random().Next(111111,999999).ToString(),
                OrderState = OrderState.Completed,
                PaymentType = PaymentType.CreditCart,
                PaymentId = payment.PaymentId,
                ConversationId = payment.ConversationId,
                OrderDate = DateTime.Now,
                FirstName = model.FirstName,
                LastName =  model.LastName,
                Email = model.Email,
                Phone = model.Phone,
                Address =  model.Address,
                City = model.City,
                UserId = userId,
                OrderItems = model.CartModel.Cart.CartItems.Select(x => new OrderItem
                {
                    Price = (decimal)x.Product.Price,
                    ProductId = x.ProductId,
                    Quantity = x.Quantity,
                }).ToList()
            };

            await _orderService.AddAsync(order);
        }

        private async Task<Cart> Cart()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            var cart = _cartService.GetCart(user);
            return cart;
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-fWpwcVa0tG93cq6igdWpm1kz4v0sgdNd";
            options.SecretKey = "sandbox-SVlpc8AbaMdgUNxFyCMX4M2cImZut8KH";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice.ToString().Split(",")[0];
            request.PaidPrice = model.CartModel.TotalPrice.ToString().Split(",")[0];
            request.Currency = "TRY";
            request.Installment = 1;
            request.BasketId = model.CartModel.Cart.Id.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvv;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;
            //paymentCard.CardHolderName = "John Doe";
            //paymentCard.CardNumber = "5528790000000008";
            //paymentCard.ExpireMonth = "12";
            //paymentCard.ExpireYear = "2030";
            //paymentCard.Cvc = "123";
            //paymentCard.RegisterCard = 0;
            //request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "John";
            buyer.Surname = "Doe";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;
            foreach (var item in model.CartModel.Cart.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.Product.Name;
                basketItem.Category1 = "Phone";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = item.Product.Price.ToString().Split(",")[0];
                basketItems.Add(basketItem);

            }


            request.BasketItems = basketItems;

            Payment payment = Payment.Create(request, options);
          
            return payment;
        }
    }
}

ShoppingApp.WebMVC/Controllers/FavoriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Entities.Models;
using ShoppingApp.Services.Abstract;

namespace ShoppingApp.WebMVC.Controllers
{
    [Authorize]
    public class FavoriteController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IFavoriteService _favoriteService;

        public FavoriteController(UserManager<User> userManager, IFavoriteService favoriteService)
        {
            _userManager = userManager;
            _favoriteService = favoriteService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var list = await _favoriteService.GetAllAsync(x => x.UserId == user.Id, x => x.Product,x=> x.User);

            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> AddToFavorite(int productId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            await _favoriteService.AddToFavorite(productId, user);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFromFavorite(int productId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            await _favoriteService.RemoveFromFavorite(productId, user);

            return RedirectToAction("Index");
        }
    }
}

ShoppingApp.WebMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingApp.Entities.Models;
using ShoppingApp.Services.Abstract;
using ShoppingApp.WebMVC.Models;

namespace ShoppingApp.WebMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly UserManager<User> _userManager;
        private readonly IFavoriteService _favoriteService;

        public ProductController(IProductService productService, UserManager<User> userManager, IFavoriteService favoriteService)
        {
            _productService = productService;
            _userManager = userManager;
            _favoriteService = favoriteService;
        }

        public async Task<IActionResult> Detail(int id)
        {
            var product = _productService.Quarayable()
                .Include(x=> x.ProductCategories)
                .ThenInclude(x=>x.Category)
                .Include(x => x.Currency)
                .FirstOrDefault(x => x.Id == id);

            var user = await _userManager.GetUserAsync(HttpContext.User);

            bool favorite = false;

            if (user != null)
            {
                favorite = await _favoriteService.AnyAsync(x => x.UserId == user.Id && x.ProductId == id);

            }



            var model = new ProductDetailModel()
            {
                Product = product,
                IsFavorite = favorite
            };

            return View(model);
        }
    }
}

ShoppingApp.WebMVC/ViewComponents/CartViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.Entities.Models;
using ShoppingApp.Services.Abstract;
using ShoppingApp.WebMVC.Models;

namespace ShoppingApp.WebMVC.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {

        private readonly ICartService _cartService;
        private readonly UserManager<User> _userManager;

        public CartViewComponent(ICartService cartService, UserManager<User> userManager)
        {
            _cartService = cartService;
            _userManager = userManager;
        }

        public IViewComponentResult Invoke()
        {
            var cart =  Cart().Result;

            var model = new CartCountModel()
            {
                CardItemCount = cart.CartItems.Count
            };

            return View(model);
        }

        private async Task<Cart> Cart()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            var cart = _cartService.GetCart(user);
            return cart;
        }
    }
}

ShoppingApp.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from demos.codeniner.com/edura/shop-catalog-sidebar-left.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 13 Jul 2017 15:11:18 GMT -->
<head>
    <!-- METAS -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- TITLE -->
    <title>Edura - Multipurpose Website Template</title>

    <!-- FAVICON -->
    <link rel="shortcut icon" href="~/theme/images/favicon.png" />

    <!-- LOAD MAIN CSS -->
    <link href="~/theme/style.css" rel="stylesheet" type="text/css">

    <!-- LOAD COLOR STYLE (OPTONAL) CSS -->
    <link href="~/theme/styles/lunar.css" rel="stylesheet" type="text/css" id="colorstyle">

    <!-- LOAD CUSTOM CSS -->
    <link href="~/theme/custom.css" rel="stylesheet" type="text/css">

    <!-- LOAD DEMO CSS -->
    <link href="~/theme/demo/demo.css" rel="stylesheet" type="text/css">
    @await Html.PartialAsync("_LayoutCssPartial")

</head>

<body>

    <!-- WRAPPER START -->
    <div id="wrapper">
        <!-- HEADER START -->
        @await Html.PartialAsync("_Navbar")

        <!-- HEADER END -->
        <!-- PAGE TITLE START -->
        <section id="title" class="container-fluid wow fadeInDown">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6">
                        <h1>Shop <small>Catalog</small></h1>
                    </div>
                </div>
            </div>
        </section>
        <!-- PAGE TITLE END -->
        <!-- CONTENT START -->
        <section id="content">
            <section id="shop" class="container">

                <div class="row">
                    @RenderBody()
                </div>
            </section>
        </section>
        <!-- CONTENT END -->
        <!-- FOOTER START -->
        <section id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <img src="images/edura-logo.png" alt="Edura - Multipurpose Website Template">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. <b>Lorem ipsum dolor sit amet, consectetur adipiscing</b>.</p>
                        <br>
                        <ul class="list-unstyled list-inline social-icons">
                            <li><a href="#" class="facebook"><i class="fa fa-facebook facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter twitter"></i></a></li>
                            <li><a href="#" class="googleplus"><i class="fa fa-google-plus googleplus"></i></a></li>
                            <li><a href="#" class="youtube"><i class="fa fa-youtube youtube"></i></a></li>
                            <li><a href="#" class="linkedin"><i class="fa fa-linkedin linkedin"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>PAGES</h4>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">HOME</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">ABOUT US</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">SERVICES</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">BLOG</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">STORE</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">PRIVACY POLICY</a></li>
                        </ul>
                    </div>

                    <div class="col-md-3">
                        <h4>CONTACT US</h4>
                        <p><i class="fa fa-map-pin fa-fw"></i> 379 5th Ave, New York, 10001, USA</p>
                        <p><i class="fa fa-phone fa-fw"></i> +(112) 345 6879</p>
                        <p><i class="fa fa-phone fa-fw"></i> +(112) 345 6879</p>
                        <p><i class="fa fa-envelope fa-fw"></i> hello@example.com</p>
                    </div>

                    <div class="col-md-3">
                        <h4>NEWSLETTER</h4>
                        <p>Subscribe to our monthly newsletter and stay updated with the latest news and info.</p>
                        <form action="#" method="post">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon"><i class="fa fa-envelope-o"></i></div>
                                    <input type="email" class="form-control" id="email" placeholder="Your Email Address" required>
                                </div>
                            </div>
                            <div class="form-group pull-right">
                                <button type="submit" class="btn btn-primary">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="row">
                    <hr>
                    <div class="col-md-12 text-center bottom">
                        <p>Copyright &copy; 2016 Codeniner. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- FOOTER END -->


    </div>
    <!-- WRAPPER END -->
    <!-- back to top button -->
    <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><span class="glyphicon glyphicon-chevron-up"></span></a>



    <!-- MAIN JS FILES REQUIRED ON ALL PAGES -->
    <script src="~/theme/vendor/jquery/jquery.min.js"></script>

    <script src="~/theme/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/theme/vendor/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js"></script>
    <script src="~/theme/vendor/wow/wow.min.js"></script>
    <script src="~/theme/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="~/theme/vendor/SmoothScroll/SmoothScroll.min.js"></script>

    <script src="~/theme/vendor/waypoints/waypoints.min.js"></script>
    <script src="~/theme/vendor/counterup/jquery.counterup.min.js"></script>


    <!-- HERO SLIDER-->
    <script src="~/theme/vendor/hero-slider/js/modernizr.js"></script>
    <script src="~/theme/vendor/hero-slider/js/main.js"></script>

    <!-- OWL CAROUSEL -->
    <script src="~/theme/vendor/owl-carousel/owl.carousel.js"></script>

    <!-- FILTERIZR -->
    <script src="~/theme/vendor/jquery/jquery.filterizr.js"></script>

    <!-- EDURA JS REQUIRED ON ALL PAGES-->
    <script src="~/theme/edura.js"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '../../www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-81122143-3', 'auto');
        ga('send', 'pageview');</script>

    <!-- STYLE SWITCHER -->
    <script src="~/theme/demo/demo.js"></script>
    @await Html.PartialAsync("_LayoutJsPartial")
    @await RenderSectionAsync("Scripts", false)
</body>

<!-- Mirrored from demos.codeniner.com/edura/shop-catalog-sidebar-left.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 13 Jul 2017 15:11:18 GMT -->
</html>

ShoppingApp.WebMVC/Views/Shared/_LayoutCssPartial.cshtml
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
<link href="https://cdn.datatables.net/buttons/1.6.3/css/buttons.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous" />

ShoppingApp.WebMVC/Views/Shared/_LayoutJsPartial.cshtml
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/js/scripts.js"></script>
<script src="~/js/site.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="~/assets/demo/chart-area-demo.js"></script>
<script src="~/assets/demo/chart-bar-demo.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="~/assets/demo/datatables-demo.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.3/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/1.6.3/js/buttons.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@@10"></script>

ShoppingApp.WebMVC/Views/Shared/_Navbar.cshtml
<section id="header">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/theme/images/edura-logo.png" alt="Edura - Multipurpose Website Template">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">@User.Identity.Name</a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Paneline Geçiş</a></li>
                                <li><a asp-controller="Favorite" asp-action="Index"><i class="fas fa-heart"></i> Favorilerim </a></li>

                            </ul>
                        </li>
                        <li>
                            <a asp-controller="Auth" asp-action="Logout" class="dropdown-toggle" >Logout</a>
                        </li>
    
                        @await Component.InvokeAsync("Cart")
                    }
                    else
                    {
                    <li>
                        <a asp-controller="Home" asp-action="Index" class="dropdown-toggle">Home</a>
                    </li>

                    <li>
                        <a asp-controller="Auth" asp-action="Login" class="dropdown-toggle" >Login</a>
                    </li>

                    <li>
                        <a asp-controller="Auth" asp-action="Register" class="dropdown-toggle">Register</a>
                    </li>
                    }
                </ul>



            </div>
        </div>
    </nav>
</section>

ShoppingApp.WebMVC/Views/Shared/_product.cshtml
@model Product

<div class="col-md-4 wow fadeInUp">
    <div class="text-center product-item">
        <div class="product-item-top">
            <img alt="" class="img-responsive" src="~/images/@Model.ImageUrl">
            <div class="mask"></div>
            <ul class="list-unstyled list-inline">
                <li><a asp-controller="Product" asp-action="Detail" asp-route-id="@Model.Id" ><i class="fa fa-link fa-fw"></i></a></li>
                <li><a asp-controller="Carts" asp-action="AddToCart" asp-route-productId="@Model.Id"><i class="fa fa-cart-plus fa-fw"></i></a></li>
            </ul>
        </div>
        <div class="product-item-inner">
            <h3 class="product-title"><a href="#">@Model.Name</a></h3>
            <p class="product-price">@Model.Currency.Symbol @Model.Price</p>
        </div>
    </div>
</div>